server:
  port: 8081
spring:
  application:
    name: foodie
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rrdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: abc80
  redis:
    host: 192.168.157.144
    port: 6379
    password: redis
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.foodie.entity # 别名扫描包
logging:
  level:
    com.foodie: debug